[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "messagemedia-simple"
version = "0.1.0"
license = "MIT"
description = "Simple MessageMedia module for sending SMS messages."
authors = ["Michael Ludvig <mludvig@logix.net.nz>"]
keywords = [ 'messagemedia', 'sms' ]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
pytest = ""
responses = ""
