version: 2.1

workflows:
  build_and_publish:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - publish:
          requires:
            - build
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+.*/
            branches:
              ignore: /.*/

jobs:
  build:
    docker:
      - image: circleci/python:3.6

    steps:
      - checkout

      - run:
          name: Install prerequisities
          command: |
            sudo pip install poetry

      - run:
          name: Run testsuite
          command: |
            poetry run tox -e py36


  publish:
    docker:
      - image: circleci/python:3.6

    steps:
      - checkout
      - run:
          name: Verify git tag vs. package version
          command: |
            PACKAGE_VERSION=$(poetry version --no-ansi | cut -d\  -f2)
            test "v${PACKAGE_VERSION}" = "${CIRCLE_TAG}"

      - run:
          name: Configure PyPi
          command: |
            poetry config repositories.test-pypi https://test.pypi.org/legacy/
            poetry config http-basic.pypi $PYPI_USERNAME $PYPI_PASSWORD

      - run:
          name: Build dist archives
          command: |
            poetry build

      - run:
          name: Publish to PyPi
          command: |
            poetry publish -r test-pypi
